### ISSUE TITLE
How about creating a pod?

### ISSUE THREAD

**Issue by viteinfinite** [funkyboy/How-To-Create-a-Rotating-Wheel-Control-with-UIKit#1]
Hi,
I created a fork of your project with some major changes. You can find it here: https://github.com/viteinfinite/SMWheelControl 

I was thinking about creating a pod to be published on CocoaPods and changing the license to a standard one (like the Apache License 2.0 or other ones).

What do you think about?

Keep me updated,
Simone

**Comment by funkyboy** [comment]
Ok for the POD. As for the license I prefer BSD3: http://opensource.org/licenses/BSD-3-Clause
